# Generated by Django 5.1.3 on 2025-03-14 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="is_active",
            field=models.BooleanField(default=django.utils.timezone.now),
        ),
    ]
