# Generated by Django 5.1.3 on 2025-03-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_listing_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="duration",
            field=models.CharField(
                choices=[
                    ("1 Day", "One Day"),
                    ("2 Days", "Two Days"),
                    ("5 Days", "Five Days"),
                    ("10 Days", "Ten Days"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="updated_bid",
            field=models.DecimalField(
                decimal_places=2, default=True, max_digits=10, null=True
            ),
        ),
    ]
