# Generated by Django 5.1.3 on 2025-03-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_comment_content_alter_listing_duration_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Content",
        ),
    ]
