# Generated by Django 5.1.3 on 2025-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_members_delete_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "firstname",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("lastname", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Members",
        ),
    ]
