# Generated by Django 5.1.3 on 2025-03-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_member_delete_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="comment",
            field=models.CharField(default=1, max_length=355),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="id",
            field=models.AutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="member",
            name="firstname",
            field=models.CharField(max_length=255),
        ),
    ]
