# Generated by Django 5.1.3 on 2025-03-19 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_member_comment_member_id_alter_member_firstname"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
            preserve_default=False,
        ),
    ]
